(define (cube n) (* n n n))
(define (even? n) (= 0 (remainder n 2)))
(define (inc n) (+ n 1))

(define (sr f a b n)
  (define h (/ (- b a) n))
  (define (coeff k) (if (even? k) 2 4))
  (define (y k) (f (+ a (* k h))))
  (define (iter k)
    (cond ((= k n) (y n))
          ((= k 0) (+ (y 0) (iter (inc k))))
          (else (+ (* (coeff k) (y k)) (iter (inc k))))))
  (* (/ h 3.0) (iter 0)))

(sr cube 0 1 100)
(sr cube 0 1 1000)
